
export const properties = [
    {
        id: 1,
        title: "3BHK Modern House",
        location: "Edappal",
        price: "₹48 Lakhs",
        priceAmount: 4800000,
        type: "House",
        beds: 3,
        baths: 2,
        area: "1500 Sqft",
        status: "For Sale",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi8pA8V7poH2C9kAt4ztfB4a76EkT5Ce0jOp88S-dM9kxiCdJ1rvtPHnx6wzb_BuFsQuFTeugcDGNDxhXy5Pw_qQk91-uRsL5aVms9HY0Y_oUoPh6I0506KLioHypX4Jfu4HDp8DksdmLC0SsS0ScBwufI4Bmr7hFbQM-CI7ElPa78AJGhCA47bevkp/s0/modern-house.jpg",
        featured: true,
    },
    {
        id: 2,
        title: "Residential Plot - 10 Cents",
        location: "Amsakachery",
        price: "₹4.5 Lakh / Cent",
        priceAmount: 450000,
        type: "Plot",
        area: "10 Cents",
        status: "For Sale",
        image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        featured: true,
    },
    {
        id: 3,
        title: "Commercial Building",
        location: "Edappal Center",
        price: "₹85 Lakhs",
        priceAmount: 8500000,
        type: "Commercial",
        area: "2000 Sqft",
        status: "For Sale",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        featured: true,
    },
    {
        id: 4,
        title: "Luxury Villa",
        location: "Malappuram",
        price: "₹95 Lakhs",
        priceAmount: 9500000,
        type: "Villa",
        beds: 4,
        baths: 4,
        area: "2500 Sqft",
        status: "For Sale",
        image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        featured: true,
    },
    {
        id: 5,
        title: "2BHK Apartment",
        location: "Edappal",
        price: "₹42 Lakhs",
        priceAmount: 4200000,
        type: "Apartment",
        beds: 2,
        baths: 2,
        area: "1100 Sqft",
        status: "For Sale",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        featured: true,
    }
    ,
    {
        id: 7,
        title: "2BHK Apartment",
        location: "Edappal",
        price: "₹42 Lakhs",
        priceAmount: 4200000,
        type: "Apartment",
        beds: 2,
        baths: 2,
        area: "1100 Sqft",
        status: "For Sale",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        featured: true,
    }
    // {
    //     id: 6,
    //     title: "Used Swift 2020",
    //     location: "Edappal",
    //     price: "₹5.2 Lakhs",
    //     priceAmount: 520000,
    //     type: "Vehicle",
    //     fuel: "Petrol",
    //     km: "25k",
    //     status: "For Sale",
    //     image: "https://images.unsplash.com/photo-1567808291548-fc3ee04dbcf3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", // Placeholder swift
    //     featured: true,
    // }
];

export const reviews = [
    {
        id: 1,
        name: "Fasil Edappal",
        rating: 5,
        text: "Best local real estate consultant. Highly recommended for quick deals.",
    },
    {
        id: 2,
        name: "Noufal AT",
        rating: 5,
        text: "Good service for buying and selling properties. Transparent process.",
    },
    {
        id: 3,
        name: "JABIR SHA",
        rating: 5,
        text: "Trustworthy sales in Edappal. Helped me find the perfect plot.",
    },
    {
        id: 4,
        name: "Riyas K",
        rating: 4,
        text: "Professional approach and good listings available.",
    },
    {
        id: 5,
        name: "Sameer V",
        rating: 5,
        text: "Very helpful and responsive. Made the paperwork easy.",
    },
    {
        id: 6,
        name: "Arun Kumar",
        rating: 5,
        text: "Great experience dealing with Sales Edappal.",
    }
];
